---
- block:
  - debug:
     msg:
     - "The FQDN hostname is.............{{ FQDN_hostname }}"
     - "The default_ipv4_address is......{{ default_ipv4_address }}"
     - ""
     - "{{ msg_string }} is Non-Compliant:"
     - "{{ check_value }}"
     - "The value should be:"
     - "{{ check_against }}"
  when: >
    check_value is not search(check_against)

- block:
  - debug:
     msg:
     - "The FQDN hostname is.............{{ FQDN_hostname }}"
     - "The default_ipv4_address is......{{ default_ipv4_address }}"
     - ""
     - "{{ msg_string }} is Compliant:"
     - "{{ check_value }}"
     - "It matches, or partially matches, the following CIS value(s):"
     - "{{ check_against }}"
  when: >
    check_value is search(check_against)
