---
- block:
  - debug:
     msg:
     - "The FQDN hostname is.............{{ FQDN_hostname }}"
     - "The default_ipv4_address is......{{ default_ipv4_address }}"
     - ""
     - "{{ msg_string }} is Non-Compliant:"
     - "{{ check_value }}"
     - "The value should be one of the following value(s):"
     - "{{ check_against }}"
  when: >
    check_value not in check_against

- block:
  - debug:
     msg:
     - "The FQDN hostname is.............{{ FQDN_hostname }}"
     - "The default_ipv4_address is......{{ default_ipv4_address }}"
     - ""
     - "{{ msg_string }} is Compliant:"
     - "{{ check_value }}"
     - "It matches the following, or one of the following, CIS value(s):"
     - "{{ check_against }}"
  when: >
    check_value in check_against
