---
galaxy_info:
  author: Richard M. Williams
  role_name: compliance-windows-security-options-policy-2016
  description: Win 2016 Check & Remediation for the CIS Security Options section
  company: 
  license: 
  min_ansible_version: 1.8
  platforms:
    - name: Windows
      versions:
        - 2008 and higher
  galaxy_tags:
    - system
    - server
    - windows
    - compliance
dependencies: []
