---
- block:
   - debug:
      msg:
       - "The FQDN hostname is.............{{ FQDN_hostname }}"
       - "The default_ipv4_address is......{{ default_ipv4_address }}"
       - ""
       - "{{ msg_string }} is Non-Compliant:"
       - "{{ check_value }}"
       - "The value should be the following or greater:"
       - "{{ check_against }}"
  when: >
    check_value|int < check_against

- block:
   - debug:
      msg:
       - "The FQDN hostname is.............{{ FQDN_hostname }}"
       - "The default_ipv4_address is......{{ default_ipv4_address }}"
       - ""
       - "{{ msg_string }} is Compliant:"
       - "{{ check_value }}"
       - "It matches, or is greater than, the following CIS value:"
       - "{{ check_against }}"
  when: >
    check_value|int >= check_against
